version: '3.8'

services:
  web:
    build: ./innowise_tech_sup
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./innowise_tech_sup/:/usr/src/innowise_tech_sup/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: ./innowise_tech_sup
    command: celery -A innowise_tech_sup worker -l info
    volumes:
      - ./innowise_tech_sup:/innowise_tech_sup
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
volumes:
  postgres_data:
  