version: '3.8'

services:
  web:
    build: ./innowise_tech_sup
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./innowise_tech_sup/:/usr/src/innowise_tech_sup/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
volumes:
  postgres_data:
    external: true